customhost = "database-1.cwcsc58b2nkb.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "eltonlooi-employee"
customregion = "us-east-1"
